MARKETPLACE="US"

REFRESH_TOKEN="YOUR_REFRESH_TOKEN"
LWA_CLIENT_ID="YOUR_LWA_CLIENT_ID"
LWA_CLIENT_SECRET="YOUR_LWA_CLIENT_SECRET"

AWS_ACCESS_KEY="YOUR_AWS_ACCESS_KEY_ID"
AWS_SECRET_KEY="YOUR_AWS_SECRET_ACCESS_KEY"
ROLE_ARN="arn:aws:iam::123456789012:role/YourSPAPIRole"
